### ISSUE TITLE
CVRmap unable to find MELODIC mixing data when res is not none

### ISSUE THREAD

**Issue by arovai** [ln2t/cvrmap#6]
This issue is migrated from #5 

```bash
singularity run --cleanenv \
                -B ${BIDS_dir}:/rawdata \
                -B ${BIDS_dir}/derivatives:/derivatives \
                -B ${fmriprep_output_dir}:/fmriprep_output \
                $BMP_3RD_PATH/cvrmap-${cvrmap_version}.sif \
                /rawdata \
                /derivatives/cvrmap-${cvrmap_version} \
                --participant_label ${subject_ID} \
                --skip_bids_validator \
                --fmriprep_dir /fmriprep_output \
                --task co2 \
                --space MNI152NLin2009cAsym:res-2 \
                participant

INFO (2024-12-09-08-11-54) Version: 2.0.25
INFO (2024-12-09-08-11-54) Indexing BIDS dataset...
INFO (2024-12-09-08-11-56) Bids directory: /rawdata
INFO (2024-12-09-08-11-56) Fmriprep directory: /fmriprep_output
INFO (2024-12-09-08-11-56) Subject(s) to analyse: ['vci016']
INFO (2024-12-09-08-11-56) Task to analyse: co2
INFO (2024-12-09-08-11-56) Selected space: MNI152NLin2009cAsym
INFO (2024-12-09-08-11-56) Selected resolution: 2
INFO (2024-12-09-08-11-56) Running for participant vci016
Traceback (most recent call last):
  File "/usr/local/bin/cvrmap", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cvrmap/cvrmap.py", line 72, in main
    melodic_mixing_df, melodic_mixing_path = get_melodic_mixing(basic_filter, layout)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cvrmap/utils/io_tools.py", line 467, in get_melodic_mixing
    melodic_mixing = layout.get(**_bids_filter)[0]
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by arovai** [comment]
@JiyangJiang this is indeed a bug, I'll do a hotfix and update the docker image asap.

**Comment by arovai** [comment]
@JiyangJiang I've pushed a new docker image for a patch, please update your docker image to version 2.0.26. Let me know how it goes for your dataset!

**Comment by JiyangJiang** [comment]
Thanks for the updates, and sorry for the delay in reply - I was on leave for 3 weeks and only come back today.

I tested version 2.0.26, but it seems there's still error.

```
singularity run --cleanenv \
>                 -B ${BIDS_dir}:/rawdata \
>                 -B ${BIDS_dir}/derivatives:/derivatives \
>                 -B ${fmriprep_output_dir}:/fmriprep_output \
>                 $BMP_3RD_PATH/cvrmap-${cvrmap_version}.sif \
>                 /rawdata \
>                 /derivatives/cvrmap-${cvrmap_version} \
>                 --participant_label ${subject_ID} \                                                                                
>                 --skip_bids_validator \                                                                                            
>                 --fmriprep_dir /fmriprep_output \                                                                                  
>                 --task co2 \                                                                                                       
>                 --space MNI152NLin2009cAsym \                                                                                      
>                 participant                                                                                                        
INFO (2025-01-06-09-32-26) Version: 2.0.26                                                                                           
INFO (2025-01-06-09-32-26) Indexing BIDS dataset...                                                                                  
INFO (2025-01-06-09-32-32) Bids directory: /rawdata                                                                                  
INFO (2025-01-06-09-32-32) Fmriprep directory: /fmriprep_output                                                                      
INFO (2025-01-06-09-32-32) Subject(s) to analyse: ['vci016']                                                                         
INFO (2025-01-06-09-32-32) Task to analyse: co2                                                                                      
INFO (2025-01-06-09-32-32) Selected space: MNI152NLin2009cAsym                                                                       
INFO (2025-01-06-09-32-32) Running for participant vci016                                                                            
Traceback (most recent call last):                                                                                                   
  File "/usr/local/bin/cvrmap", line 8, in <module>                                                                                  
    sys.exit(main())                                                                                                                 
             ^^^^^^                                                                                                                  
  File "/usr/local/lib/python3.11/site-packages/cvrmap/cvrmap.py", line 90, in main                                                  
    physio = get_physio_data(basic_filter, layout)                                                                                   
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                   
  File "/usr/local/lib/python3.11/site-packages/cvrmap/utils/io_tools.py", line 427, in get_physio_data                              
    physio.bids_load(layout, physio_filter, 'timecourse', **{'col': 1})                                                              
  File "/usr/local/lib/python3.11/site-packages/cvrmap/utils/processing.py", line 64, in bids_load                                   
    data = numpy.loadtxt(data_path, usecols=kwargs['col'])                                                                           
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                           
  File "/usr/local/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1356, in loadtxt                                           
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,                                                            
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/numpy/lib/npyio.py", line 999, in _read
    arr = _load_from_filelike(
          ^^^^^^^^^^^^^^^^^^^^
ValueError: invalid column index 1 at row 1 with 1 columns
```

**Comment by arovai** [comment]
Hello
no problem.
This error seems to be exactly the same as issue #7 . Have you tried what I suggested in this discussion?
I am closing this topic; feel free to reopen if necessary.
