### ISSUE TITLE
Error while loading physio data

### ISSUE THREAD

**Issue by arovai** [ln2t/cvrmap#7]
This issue is migrated from #5 

```bash
singularity run --cleanenv \
                -B ${BIDS_dir}:/rawdata \
                -B ${BIDS_dir}/derivatives:/derivatives \
                -B ${fmriprep_output_dir}:/fmriprep_output \
                $BMP_3RD_PATH/cvrmap-${cvrmap_version}.sif \
                /rawdata \
                /derivatives/cvrmap-${cvrmap_version} \
                --participant_label ${subject_ID} \
                --skip_bids_validator \
                --fmriprep_dir /fmriprep_output \
                --task co2 \
                --space MNI152NLin2009cAsym \
                participant

INFO (2024-12-09-10-05-22) Version: 2.0.25
INFO (2024-12-09-10-05-22) Indexing BIDS dataset...
INFO (2024-12-09-10-05-24) Bids directory: /rawdata
INFO (2024-12-09-10-05-24) Fmriprep directory: /fmriprep_output
INFO (2024-12-09-10-05-24) Subject(s) to analyse: ['vci016']
INFO (2024-12-09-10-05-24) Task to analyse: co2
INFO (2024-12-09-10-05-24) Selected space: MNI152NLin2009cAsym
INFO (2024-12-09-10-05-24) Running for participant vci016
Traceback (most recent call last):
  File "/usr/local/bin/cvrmap", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cvrmap/cvrmap.py", line 90, in main
    physio = get_physio_data(basic_filter, layout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cvrmap/utils/io_tools.py", line 427, in get_physio_data
    physio.bids_load(layout, physio_filter, 'timecourse', **{'col': 1})
  File "/usr/local/lib/python3.11/site-packages/cvrmap/utils/processing.py", line 64, in bids_load
    data = numpy.loadtxt(data_path, usecols=kwargs['col'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1356, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/numpy/lib/npyio.py", line 999, in _read
    arr = _load_from_filelike(
          ^^^^^^^^^^^^^^^^^^^^
ValueError: invalid column index 1 at row 1 with 1 columns
```

**Comment by arovai** [comment]
@JiyangJiang could you please show the first lines of you physio data file to make sure it looks as CVRmap is expecting?

**Comment by JiyangJiang** [comment]
Please see the physio data and json files below:

sub-vci016_task-co2_dir-PA_physio.tsv :

```
> head -n100 sub-vci016_task-co2_dir-PA_physio.tsv
4
4
4
3
3
3
3
3
3
3
3
3
3
3
2
3
3
6
12
18
24
28
31
33
34
35
36
37
37
37
38
40
41
42
43
43
44
44
45
45
46
46
46
46
47
47
47
47
47
47
47
47
47
47
47
47
47
45
36
26
18
13
11
8
7
6
5
4
4
4
3
3
3
3
3
3
3
3
3
3
3
3
3
3
7
13
19
24
29
32
34
36
38
39
40
40
41
41
41
41
```
sub-vci016_task-co2_dir-PA_physio.json :

```
cat sub-vci016_task-co2_dir-PA_physio.json
{
  "SamplingFrequency": 4,
  "StartTime": 0,
  "Columns": "co2",
  "co2": {
    "Units": "mmHg"
  }
}
```

**Comment by arovai** [comment]
This is a bug, thanks for reporting!
I'll add a fix when I have some time, but to easily circumvent it you could copy the co2 reading to have two (identical) columns in all you physio files.
So for instance the one you share should look like (the delimiter is a white space, not a tab):
```bash
4	4
4	4
4	4
3	3
3	3
3	3
3	3
3	3
3	3
3	3
3	3
3	3
3	3
3	3
2	2
3	3
3	3
6	6
12	12
18	18
24	24
28	28
31	31
33	33
(etc)
```
Again, this is just a quick fix to hopefully allow you to move forward with your analysis, and the code will be fixed in due time. Thank you for your understanding!
Let me know how it goes!

**Comment by arovai** [comment]
@JiyangJiang Hello! Did you get the chance to test this? Let me know if you encounter any trouble.

**Comment by JiyangJiang** [comment]
Hi @arovai, 

The pipeline ran successfully after implementing what you suggested.

Thanks,
Jiyang
